### ISSUE TITLE
Add "all/none" toggle to builder filters on Dart Results Feed

### ISSUE THREAD

**Issue by nshahan** [dart-lang/dart_ci#58]
If I want to see only builder on the results feed it would be much easier if I could toggle all of them off easily then just select the one I want. 

Conversely if I want to switch back to all builders there should be a simple way to this with once click.

I think a common UI pattern for a long list of check boxes is to include an All/None option that when clicked forces all options to be checked or unchecked.

**Comment by whesse** [comment]
I can add that, but the "none" button has to leave at least one configuration group checked.  It could leave the top one checked, then you can check the one you want, and then uncheck the top one.

The list has logic ensuring that you don't uncheck the last checked configuration.
Putting on the "Features" project, giving a priority.

**Comment by whesse** [comment]
The configuration groups filter now is modified so "none" (no checkboxes selected) means the filter is not active.  So the default state is now "none", and checking a single one turns on the filter and selects only the checked groups.

Right now I'm working on a redesign that puts these in the filter bar, and adds the per-test and per-configuration filtering, so the entire filter popup will be removed.

Marking as fixed, since the usability problem is already fixed (unless the case where you want "all but analyzer" groups is important, since that would require checking lots of boxes).
